import { ProductList } from "./productList.modules";

export interface Cart {
    cartId: Number,
    userId: String,
    shopId: String,
    createdOn: String,
    gstAmount: Number,
    totalAmount: Number,
    transactionId: String,
    paid: Number,
    dues: Number,
    orderStatus: Number,
    transactionType: Number,
    orderDate: String,
    deliveryCharge: Number,
    price: Number,
    discount: Number,
    orderType: Number,
    addressId: Number,
    mobileNo: String,
    userName: String,
    review: String,
    slotDate: String,
    deliveryDate: String,
    description: String,
    shippingId: String,
    deliveryType: Number,
    shippingDate: String,
    shippingName: String,
    dBoyName: String,
    dBoyNumber: String,
    courierName: String,
    shopName: String,
    adminId: String,
    payableAmount: Number,
    otp: Number,
    insideShop: Boolean,
    bundleDiscount: Number,
    productList: ProductList[],
    address: String,
    active: Boolean,
    deleted: Boolean,
    offline: Boolean
}