export const ProductActions = {
    GET_BY_SHOP_ID: "GET_PRODUCT_BY_SHOP_ID",
    GET_BY_SHOP_ID_ASYNC: "GET_PRODUCT_BY_SHOP_ID_ASYNC",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    SET_PRODUCT_VARIANT_ASYNC: "SET_PRODUCT_VARIANT_ASYNC",
    SET_PRODUCT_VARIANT: "SET_PRODUCT_VARIANT"
}

export const BrandActions = {
    GET_BY_SHOP_ID: "GET_BRAND_BY_SHOP_ID",
    GET_BY_SHOP_ID_ASYNC: "GET_BRAND_BY_SHOP_ID_ASYNC",
    BRAND_ERROR: "BRAND_ERROR"
}

export const CategoryActions = {
    GET_BY_SHOP_ID: "GET_CATEGORY_BY_SHOP_ID",
    GET_BY_SHOP_ID_ASYNC: "GET_CATEGORY_BY_SHOP_ID_ASYNC",
    CATEGORY_ERROR: "CATEGORY_ERROR"
}

export const UserActions = {
    GET_BY_ID: "GET_USER_BY_ID",
    GET_BY_ID_ASYNC: "GET_USER_BY_ID_ASYNC",
    USER_ERROR: "USER_ERROR"
}

export const VarientActions = {
    GET_BY_SHOP_ID: "GET_VARIENT_BY_SHOP_ID",
    GET_BY_SHOP_ID_ASYNC: "GET_VARIENT_BY_SHOP_ID_ASYNC",
    VARIENT_ERROR: "VARIENT_ERROR"
}

export const MeasurementActions = {
    GET_BY_SHOP_ID: "GET_MEASUREMENT_BY_SHOP_ID",
    GET_BY_SHOP_ID_ASYNC: "GET_MEASUREMENT_BY_SHOP_ID_ASYNC",
    MEASUREMENT_ERROR: "MEASUREMENT_ERROR"
}

export const CartActions = {
    GET_BY_SHOP_ID_USER_ID: "GET_CART_BY_SHOP_ID_USER_ID",
    GET_BY_SHOP_ID_USER_ID_ASYNC: "GET_CART_BY_SHOP_ID_USER_ID_ASYNC",
    CART_ERROR: "CART_ERROR"
}
